const API='../backend/api';
const state={products:[],filtered:[],category:'All',search:'',cart:JSON.parse(localStorage.getItem('ecommerce_cart')||'[]')};
const $=s=>document.querySelector(s); const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
async function loadProducts(){try{const r=await fetch(`${API}/products.php`);if(!r.ok)throw Error();state.products=await r.json();apply()}catch(e){$('#count').textContent='Backend unavailable';$('#grid').innerHTML='<div class="empty" style="grid-column:1/-1"><h3>Could not connect to PHP backend</h3><p>Start Apache and MySQL in XAMPP, import the database, then open this site from localhost.</p></div>'}}
function apply(){const q=state.search.toLowerCase().trim();state.filtered=state.products.filter(p=>(state.category==='All'||p.category===state.category)&&(!q||(`${p.name} ${p.category}`).toLowerCase().includes(q)));render()}
function render(){const grid=$('#grid');$('#count').textContent=`${state.filtered.length} product${state.filtered.length===1?'':'s'}`;$('#empty').classList.toggle('hidden',state.filtered.length>0);grid.innerHTML=state.filtered.map(p=>{const dis=p.origPrice>p.price?Math.round((1-p.price/p.origPrice)*100):0;return `<article class="card"><div class="pic">${dis?`<span class="sale">${dis}% OFF</span>`:''}<img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy" onerror="this.src='https://placehold.co/700x875/e9e4da/333?text=Bhaskar+Store'"></div><div class="info"><div class="type">${esc(p.category)}</div><div class="name">${esc(p.name)}</div><div class="prices"><b>${money(p.price)}</b>${p.origPrice>p.price?`<span class="old">${money(p.origPrice)}</span>`:''}</div><button class="add" data-id="${p.id}" ${Number(p.stock)<=0?'disabled':''}>${Number(p.stock)<=0?'OUT OF STOCK':'ADD TO BAG'}</button></div></article>`}).join('');grid.querySelectorAll('.add').forEach(b=>b.onclick=()=>add(+b.dataset.id))}
function add(id){const p=state.products.find(x=>+x.id===id);if(!p)return;let i=state.cart.find(x=>+x.id===id);if(i)i.qty++;else state.cart.push({id,qty:1,name:p.name,price:+p.price,image:p.image});save();toast('Added to your bag')}
function save(){localStorage.setItem('ecommerce_cart',JSON.stringify(state.cart));cartRender()}
function cartRender(){let qty=state.cart.reduce((a,x)=>a+x.qty,0),sum=state.cart.reduce((a,x)=>a+x.qty*x.price,0);$('#bagCount').textContent=qty;$('#subtotal').textContent=money(sum);$('#total').textContent=money(sum);$('#modalTotal').textContent=money(sum);$('#cartItems').innerHTML=state.cart.length?state.cart.map(i=>`<div class="cart-row"><img src="${esc(i.image)}"><div><h4>${esc(i.name)}</h4><small>${money(i.price)}</small><div class="qty"><button data-dec="${i.id}">−</button><b>${i.qty}</b><button data-inc="${i.id}">+</button></div><button class="remove" data-rem="${i.id}">Remove</button></div><strong>${money(i.price*i.qty)}</strong></div>`).join(''):'<div class="empty"><h3>Your bag is empty</h3><p>Add products from the collection.</p></div>';$('#cartItems').querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>change(+b.dataset.inc,1));$('#cartItems').querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>change(+b.dataset.dec,-1));$('#cartItems').querySelectorAll('[data-rem]').forEach(b=>b.onclick=()=>remove(+b.dataset.rem))}
function change(id,d){let i=state.cart.find(x=>+x.id===id);if(!i)return;i.qty+=d;if(i.qty<1)state.cart=state.cart.filter(x=>+x.id!==id);save()}function remove(id){state.cart=state.cart.filter(x=>+x.id!==id);save()}
function openBag(){ $('#drawer').classList.add('open');$('#shade').classList.add('show')}function closeBag(){$('#drawer').classList.remove('open');$('#shade').classList.remove('show')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1700)}
$('#searchForm').onsubmit=e=>{e.preventDefault();state.search=$('#search').value;apply();$('#shop').scrollIntoView({behavior:'smooth'})};$('#search').oninput=e=>{state.search=e.target.value;apply()};document.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{document.querySelectorAll('.cat').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.category=b.dataset.cat;apply()});$('#startShopping').onclick=()=>$('#shop').scrollIntoView({behavior:'smooth'});$('#ethnicBtn').onclick=()=>{state.category='Ethnic';document.querySelectorAll('.cat').forEach(x=>x.classList.toggle('active',x.dataset.cat==='Ethnic'));apply();$('#shop').scrollIntoView({behavior:'smooth'})};$('#reset').onclick=()=>{state.category='All';state.search='';$('#search').value='';document.querySelectorAll('.cat').forEach(x=>x.classList.toggle('active',x.dataset.cat==='All'));apply()};$('#bagBtn').onclick=openBag;$('#closeBag').onclick=closeBag;$('#shade').onclick=closeBag;
$('#checkoutBtn').onclick=()=>{if(!state.cart.length)return toast('Your bag is empty');closeBag();$('#modal').classList.remove('hidden')};$('.modal-x').onclick=()=>$('#modal').classList.add('hidden');$('#loginBtn').onclick=()=>$('#loginModal').classList.remove('hidden');$('.close-login').onclick=()=>$('#loginModal').classList.add('hidden');
$('#login').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const msg=$('#loginMsg');msg.textContent='Signing in...';try{const r=await fetch(`${API}/login.php`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(d)});const text=await r.text();let j;try{j=JSON.parse(text)}catch{throw Error('PHP backend returned an invalid response. Check XAMPP/MySQL and the PHP error log.')}if(!r.ok||!j.success)throw Error(j.error||'Login failed');localStorage.setItem('ecommerce_user',JSON.stringify(j.user));$('#checkoutUser').value=j.user.username;msg.textContent=`Welcome, ${j.user.full_name}.`;msg.style.color='green';setTimeout(()=>{$('#loginModal').classList.add('hidden');msg.textContent=''},700)}catch(x){console.error(x);msg.textContent=x.message;msg.style.color='red'}};
$('#register').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{const r=await fetch(`${API}/register.php`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(d)}),j=await r.json();if(!r.ok)throw Error(j.error);$('#registerMsg').textContent='Account created. You can sign in now.';e.target.reset()}catch(x){$('#registerMsg').textContent=x.message}};
$('#checkout').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const pin=d.pin;delete d.pin;d.address=`${d.address}, ${pin}`;d.items=state.cart.map(i=>({id:i.id,qty:i.qty}));$('#checkoutMsg').textContent='Placing order...';try{const r=await fetch(`${API}/checkout.php`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(d)}),j=await r.json();if(!r.ok)throw Error(j.error);$('#checkoutMsg').textContent=`Order ${j.orderId} placed successfully. Transaction ${j.txnId}.`;state.cart=[];save();loadProducts();setTimeout(()=>$('#modal').classList.add('hidden'),1800)}catch(x){$('#checkoutMsg').textContent=x.message}};
async function restoreSession(){try{const r=await fetch(`${API}/me.php`,{credentials:'same-origin'});if(!r.ok){localStorage.removeItem('ecommerce_user');return}const j=await r.json();if(j.success&&j.user){localStorage.setItem('ecommerce_user',JSON.stringify(j.user));$('#checkoutUser').value=j.user.username}}catch(e){console.warn('Session restore failed',e)}}cartRender();loadProducts();restoreSession();
